version: '3.8'

services:
  channel-adapter-api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
      - ./test_audio:/app/test_audio
    environment:
      - PYTHONPATH=/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
